spring:
  application:
    name: equip-rental
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 명백하게 명시만 해두면 안전하지만, 없어도 기본값이 SpringPhysicalNamingStrategy
        spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          time-zone: Asia/Seoul
  mustache:
    enabled: true
    charset: UTF-8
    suffix: .html
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 10MB     # 단일 파일 최대 업로드 크기
      max-request-size: 20MB  # 전체 요청(여러 파일 합산) 최대 크기

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    p6spy: DEBUG
    com.p6spy.engine.spy: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8    # 문자 인코딩을 UTF-8로 설정
      enabled: true     # 인코딩 설정을 활성화
      force: true       # 요청과 응답 모두 강제로 UTF-8 적용