version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: equip-rental
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}                  # DB 이름
      MYSQL_USER: ${DB_USER}                      # 일반 사용자
      MYSQL_PASSWORD: ${DB_PASSWORD}              # 일반 사용자 비밀번호
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
    ports:
      - "${MYSQL_HOST_PORT}:3306"   # 호스트 포트 : 컨테이너 포트 3306
    volumes:
      - ./mysql-init/:/docker-entrypoint-initdb.d/